pkgs.sudo
pkgs.curl
pkgs.wget
pkgs.dpkg
pkgs.apt
pkgs.git
pkgs.libglib2.0-dev
pkgs.libfdt-dev
pkgs.libpixman-1-dev
pkgs.zlib1g-dev
pkgs.ninja-build
pkgs.qemu-kvm
pkgs.libvirt-daemon-system
pkgs.bridge-utils
pkgs.virt-manager
pkgs.uml-utilities
pkgs.qemu-system
pkgs.frp
pkgs.nginx
pkgs.tailscale